### ISSUE TITLE
Open Pilot and Checkbox "Check for updates" result in crash.

### ISSUE THREAD

**Issue by UEAdmiral** [RyuKojiro/novafix#12]
Prior to posting this here, I reinstalled EV Nova 1.1.1 from AmbrosiaSW's page and ran Novafix over it. It did not resolve the issue. Unlike a previous post, gambling seems to be fine. No crashes there. 

Open Pilot crash report: https://pastebin.com/cpcanXcB
Set Prefs > Check For Updates crash report: https://pastebin.com/CRsYTjNZ

Thoughts?

**Comment by RyuKojiro** [comment]
I'm pretty sure this has to do with the dyld cache. Can you follow the steps below and let me know if it resolves your issue?

1) `make uninstall` to remove novafix
2) Run the EV app, and let it crash on launch, since novafix is not in place
3) `make install` to reinstall novafix
4) Launch EV again, and try to Open Pilot

**Comment by UEAdmiral** [comment]
On my way to bed, but I'll try tomorrow. I've no idea how to 'make uninstall' or 'make install'. If you're feeling particularly generous, a step-by-step for the technically barely literate, that'd make things easier, but I'm sure with a bit of googling tomorrow I could figure it out.

**Comment by UEAdmiral** [comment]
Okay, a friend explained to me that "make uninstall" was a Terminal prompt and gave me a step-by-step of how to perform it. This fixed the issue. Thank you, RyuKojiro. 

For anybody else running into this who is equally technically illiterate, do the following: 
1. Download the novafix sourcecode
2. Navigate to resulting folder (novafix-master, unless you renamed it)
3. Open Terminal and input "cd " (with the space, sans-quotes) and either drag & drop the Novafix-master folder into the terminal window or manually input the file path, and hit enter. This will navigate you to the folder in the command line. 
4. input "make uninstall" and press enter (just that, no file specified or anything, you're telling it to uninstall the contents of the directory you've navigated to). Don't close Terminal yet. 
5. Do as Ryu mentioned, and run EV Nova.app, letting it crash, etc.
6. Go back to Terminal, input "make install" (if you closed terminal you'll have to re-navigate to novafix-master again as above)

And you should be all good.

**Comment by RyuKojiro** [comment]
That confirms the GLEngine issue is fixed by these steps. Thanks!
