### ISSUE TITLE
macOS 10.14

### ISSUE THREAD

**Issue by MarkYSA** [RyuKojiro/novafix#13]
Hi,

I get the following errors on my Mac book with latest Darwin release Mojave:

 make install
cc -arch i386   -c -o spi.o spi.c
cc -dynamiclib -arch i386 spi.o -o libNova.A.dylib
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
Undefined symbols for architecture i386:
  "___stderrp", referenced from:
      _CGSSetWindowDepthLimit in spi.o
  "_fprintf", referenced from:
      _CGSSetWindowDepthLimit in spi.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libNova.A.dylib] Error 1

Regards,
Mark

**Comment by openfirmware** [comment]
I also was unable to compile the patch under Mojave. However if you have access to a High Sierra system, you can patch EV Nova there and then copy the application to Mojave where it will run.

**Comment by RyuKojiro** [comment]
Yeah, 32-bit support was removed from the SDK. I removed the only code that required any linkage, since clang can still emit 32-bit binaries. Try building again after pulling the latest commit.
