### ISSUE TITLE
"Open Pilot" causes crash on OSX10.11.1

### ISSUE THREAD

**Issue by mattsoulanille** [RyuKojiro/novafix#7]
When clicking "Open Pilot," Nova crashes and produces the following crash report:

> ...
> Crashed Thread:        0  Dispatch queue: com.apple.main-thread
> 
> Exception Type:        EXC_BREAKPOINT (SIGTRAP)
> Exception Codes:       0x0000000000000002, 0x0000000000000000
> 
> Dyld Error Message:
>  Symbol not found: _gliCreateContextWithShared
>  Referenced from: >/System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine
>  Expected in: flat namespace
> ...

**Comment by mattsoulanille** [comment]
Going to a spaceport bar and gambling also produces the same crash.

**Comment by dschwartz783** [comment]
I am not seeing this crash. Is it possible your installation is corrupted? Try reinstalling the game and patch it with novafix again, and see if that resolves the issue.

**Comment by RyuKojiro** [comment]
I just now loaded a pilot, jumped back to Sol, and gambled on blue. I didn't get any crashes. I'd try reinstalling the game (also making sure you are up-to-date).
